name: Publish to PyPI
on:
  push:
    branches:
      - master
    paths:
      - setup.cfg
      - setup.py
jobs:
  build-and-publish:
    name: Build and publish python distributions to PyPI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Python 3.8
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: python -m pip install --user build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
