name: Publish to PyPI
on:
  push:
    branches: ["main"]
    paths:
      - pyproject.toml
      - setup.cfg
      - setup.py

env:
  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  build-and-publish:
    name: Build and publish python distributions to PyPI
    runs-on: ubuntu-20.04

    steps:
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: master
          check-name: Validation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Python 3.8
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install poetry
        run: python -m pip install --user poetry

      - name: Build a binary wheel and a source tarball
        run: python -m poetry build

      - name: Publish distribution to PyPI
        run: python -m poetry publish
